// index.ts | Blueberry - ultraviolet port for Bun

// ── Core exports ──
export {
  type Cell,
  newCell,
  emptyCell,
  EmptyCell,
  isZero,
  cellEquals,
} from "./cell"

export {
  type Style,
  type StyledSpan,
  type Underline,
  StyledString,
  styleToString,
  styleDiff,
  stylesEqual,
  isStyleEmpty,
  stripAnsi,
} from "./styled"

export {
  ScreenBuffer,
} from "./buffer"

export {
  TerminalRenderer,
} from "./terminal_renderer"

export {
  type TerminalEvent,
  type KeyEvent,
  type MouseClickEvent,
  type MouseReleaseEvent,
  type MouseWheelEvent,
  type MouseMotionEvent,
  type CursorPositionEvent,
  type WindowSizeEvent,
  type PixelSizeEvent,
  type CellSizeEvent,
  type FocusEvent,
  type BlurEvent,
  type DarkColorSchemeEvent,
  type LightColorSchemeEvent,
  type PasteEvent,
  type PasteStartEvent,
  type PasteEndEvent,
  type TerminalVersionEvent,
  type ModifyOtherKeysEvent,
  type KeyboardEnhancementsEvent,
  type PrimaryDeviceAttributesEvent,
  type SecondaryDeviceAttributesEvent,
  type ModeReportEvent,
  type UnknownEvent,
} from "./events"

export {
  type Key,
  keyMatchString,
  keyString,
  keyKeystroke,
  ModShift,
  ModAlt,
  ModCtrl,
  ModMeta,
  ModHyper,
  ModSuper,
  ModCapsLock,
  ModNumLock,
  ModScrollLock,
  KeyExtended,
  KeyUp,
  KeyDown,
  KeyRight,
  KeyLeft,
  KeyBegin,
  KeyFind,
  KeyInsert,
  KeyDelete,
  KeySelect,
  KeyPgUp,
  KeyPgDown,
  KeyHome,
  KeyEnd,
  KeyKpEnter,
  KeyKpEqual,
  KeyKpMultiply,
  KeyKpPlus,
  KeyKpComma,
  KeyKpMinus,
  KeyKpDecimal,
  KeyKpDivide,
  KeyKp0,
  KeyKp1,
  KeyKp2,
  KeyKp3,
  KeyKp4,
  KeyKp5,
  KeyKp6,
  KeyKp7,
  KeyKp8,
  KeyKp9,
  KeyKpSep,
  KeyKpUp,
  KeyKpDown,
  KeyKpLeft,
  KeyKpRight,
  KeyKpPgUp,
  KeyKpPgDown,
  KeyKpHome,
  KeyKpEnd,
  KeyKpInsert,
  KeyKpDelete,
  KeyKpBegin,
  KeyF1,
  KeyF2,
  KeyF3,
  KeyF4,
  KeyF5,
  KeyF6,
  KeyF7,
  KeyF8,
  KeyF9,
  KeyF10,
  KeyF11,
  KeyF12,
  KeyF13,
  KeyF14,
  KeyF15,
  KeyF16,
  KeyF17,
  KeyF18,
  KeyF19,
  KeyF20,
  KeyF21,
  KeyF22,
  KeyF23,
  KeyF24,
  KeyF25,
  KeyF26,
  KeyF27,
  KeyF28,
  KeyF29,
  KeyF30,
  KeyF31,
  KeyF32,
  KeyF33,
  KeyF34,
  KeyF35,
  KeyF36,
  KeyF37,
  KeyF38,
  KeyF39,
  KeyF40,
  KeyF41,
  KeyF42,
  KeyF43,
  KeyF44,
  KeyF45,
  KeyF46,
  KeyF47,
  KeyF48,
  KeyF49,
  KeyF50,
  KeyF51,
  KeyF52,
  KeyF53,
  KeyF54,
  KeyF55,
  KeyF56,
  KeyF57,
  KeyF58,
  KeyF59,
  KeyF60,
  KeyF61,
  KeyF62,
  KeyF63,
  KeyCapsLock,
  KeyScrollLock,
  KeyNumLock,
  KeyPrintScreen,
  KeyPause,
  KeyMenu,
  KeyMediaPlay,
  KeyMediaPause,
  KeyMediaPlayPause,
  KeyMediaReverse,
  KeyMediaStop,
  KeyMediaFastForward,
  KeyMediaRewind,
  KeyMediaNext,
  KeyMediaPrev,
  KeyMediaRecord,
  KeyLowerVol,
  KeyRaiseVol,
  KeyMute,
  KeyLeftShift,
  KeyLeftAlt,
  KeyLeftCtrl,
  KeyLeftSuper,
  KeyLeftHyper,
  KeyLeftMeta,
  KeyRightShift,
  KeyRightAlt,
  KeyRightCtrl,
  KeyRightSuper,
  KeyRightHyper,
  KeyRightMeta,
  KeyIsoLevel3Shift,
  KeyIsoLevel5Shift,
  KeyBackspace,
  KeyTab,
  KeyEnter,
  KeyReturn,
  KeyEscape,
  KeyEsc,
  KeySpace,
} from "./keys"

export {
  type Mouse,
  MouseMode,
  MouseEncoding,
  MouseButton,
  mouseString,
  mousePixelToCell,
} from "./mouse"

export {
  Terminal,
  type TerminalOptions,
} from "./terminal"

// ── Ultraviolet-compatible re-exports ──
export {
  AttrBold, AttrFaint, AttrItalic, AttrBlink, AttrRapidBlink,
  AttrReverse, AttrConceal, AttrStrikethrough, AttrReset, AttrSlowBlink,
  UnderlineNone, UnderlineSingle, UnderlineDouble, UnderlineCurly,
  UnderlineDotted, UnderlineDashed,
  UnderlineStyleNone, UnderlineStyleSingle, UnderlineStyleDouble,
  UnderlineStyleCurly, UnderlineStyleDotted, UnderlineStyleDashed,
  Horizontal, Vertical, Left, Right,
  NormalBorder, RoundedBorder, DoubleBorder, ThickBorder,
  HiddenBorder, BlockBorder, InnerHalfBlockBorder, OuterHalfBlockBorder,
  MarkdownBorder, ASCIIBorder,
  Rect, NewLink, ReadLink, ConvertLink,
  ConvertStyle, StyleDiff,
  NewCell, TrimSpace, Logger, Environ,
  EncodeBackgroundColor, EncodeBracketedPaste, EncodeCursorColor,
  EncodeCursorStyle, EncodeForegroundColor, EncodeKeyboardEnhancements,
  EncodeMouseEncoding, EncodeMouseMode, EncodeProgressBar, EncodeWindowTitle,
  ErrCanceled, ErrInvalidDimensions, ErrReaderNotStarted,
  MouseNone, MouseLeft, MouseMiddle, MouseRight, MouseBackward, MouseForward,
  MouseModeNone, MouseModePress, MouseButton10, MouseButton11,
  MouseWheelDown, MouseWheelUp, MouseWheelLeft, MouseWheelRight,
  CursorBar, CursorBlock, CursorUnderline, CursorShape,
  ClipboardSelection, PrimaryClipboard, SystemClipboard,
  DefaultTabStops, TabStops,
  DefaultConsole, DefaultTerminal, DefaultOptions,
  ControllingConsole, ControllingTerminal,
  LegacyKeyEncoding, Suspend, NotifyWinch, NotifyWinchContext,
  OpenTTY, File, TTY, Console,
  Window, NewWindow, Winsize, SizeNotifier,
  Pos, New, Options, NewProgressBar, NewSizeNotifier,
  NewTabStops, NewKeyboardEnhancements, NewCursor, NewContext, NewCancelReader,
  ProgressBarDefault, ProgressBarError, ProgressBarIndeterminate,
  ProgressBarNone, ProgressBarState, ProgressBarWarning,
  NewStyledString,
} from "./compat"

export type {
  Underline, UnderlineStyle as UVUnderlineStyle,
  Direction, Side, Position as UVPosition,
  Border, Rectangle, Size, Link, WidthMethod,
  Drawable, DrawableFunc, LineData, Splitted,
} from "./compat"
